menu:
  首页: /
  文章: /archives
  实验室: /lab
  关于: /about
  Rss: /atom.xml

widgets: 
- search
- category
- weibo
- tag
- blogroll

excerpt_link: 阅读全文

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: true
rss: /atom.xml